baseUrl: http://localhost:3000
facebook:
  appId: '1430649763878341'
sequelize:
  database: database
  username: root
  password:
azureStorage:
  accountName: devstoreaccount1
  accountKey: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
  container: isicphotocomp
sizes:
  minimum: 1600
  large: 1280
  medium: 640
  thumbnail: 240
secret: TAEcfqXAxLJkbGUhvyVndRmK
favicon: http://static.wixstatic.com/ficons/89355b_8adb1bc8d31a9b11a84eec6107dc1b89_fi.ico