baseUrl: http://localhost:3000
facebook:
  appId: '1430649763878341'
sequelize:
  database: database
  username: root
  password:
sizes:
  large: 1280
  medium: 640
  thumbnail: 240
secret: TAEcfqXAxLJkbGUhvyVndRmK
favicon: http://static.wixstatic.com/ficons/89355b_8adb1bc8d31a9b11a84eec6107dc1b89_fi.ico