baseUrl: http://localhost:3000
facebook:
  appId: '1430649763878341'
sequelize:
  database: database
  username: root
  password:
azureStorage:
  accountName: devstoreaccount1
  accountKey: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
  container: isicphotocomp
sizes:
  minimum: 1600
  large: 1280
  medium: 640
  small: 320
  thumbnail: 240
secret: TAEcfqXAxLJkbGUhvyVndRmK
favicon: http://static.wixstatic.com/ficons/89355b_8adb1bc8d31a9b11a84eec6107dc1b89_fi.ico
categories:
  herethere:
    title: Indonesia Here and There
    description: >-
      Places, sceneries, events, architecture, arts and crafts,
      or even foods that make you think of Indonesia.
      They could be taken in Indonesia or anywhere else in the world.
  people:
    title: Indonesian People Then and Now
    description: >-
      People who hold on to Indonesian culture and traditions,
      or people who depict the current state of Indonesia.
      They could be Indonesian or non-Indonesian people.
  redwhite:
    title: Red and White
    description: >-
      These are the colours of Indonesian flag.
      Red represents bravery and white represents purity.